### ISSUE TITLE
Using variables in notification content

### ISSUE THREAD

**Issue by damiencuvillier** [nanego/redmine_unregistered_watchers#3]
I've tried to use `<<var>>` syntax, but email notification do not replace `<<var>>` syntax with its value. 

I've tried to use following syntax in footer 
```
<<subject>>
Statut : <<status>>

Comment : 
<<last_note>>
```

Besides, is it possible to use html tags to improve text look & feel

**Comment by damiencuvillier** [comment]
maybe issue is linked to markdown rendering feature ?

**Comment by nanego** [comment]
The `<<var>>` syntax only work in messages bodies. They are not processed if you use them in Signature or Footer sections.
I have just added some tests to ensure this functionality works properly.

About HTML tags, you can use them in messages. They should just work fine.
