### ISSUE TITLE
Private note as last_note

### ISSUE THREAD

**Issue by damiencuvillier** [nanego/redmine_unregistered_watchers#5]
Last note privacy is not taken in account. 

When you use ```<<last_note>> ``` var in email notification template, the last not is used, even if it's marked as private.  

Bad way I think : in my case, I use the plugins to inform my customer, at the end of issue resolution process, and I do not want to send him private note

**Comment by damiencuvillier** [comment]
I think there is something to do on line 34 of of `issue_patch.rb` file 
But I'm to dummy in ruby to make it, sorry 
```ruby
 def last_note
    self.journals.map(&:notes).reject(&:blank?).first
  end
```

**Comment by nanego** [comment]
This issue should have been fixed with the latest commits.
Please give it a try and let me know if it works as expected.

**Comment by nanego** [comment]
Thanks for reporting the issue.
