### ISSUE TITLE
n-1 note as <<last_note>>

### ISSUE THREAD

**Issue by damiencuvillier** [nanego/redmine_unregistered_watchers#6]
On the plugin use, the note that is taken as ```<<last_note>>``` is not last one. 

When I save issue, by 
* adding a unregistered watcher
* adding a new note

I think plugin process runs before saving process and it takes the previous note actually. 

I have to save also twice : 
* 1 first time to add my note
* second time to save my new watcher and change status and also notify him

**Comment by nanego** [comment]
I have just fixed the last_note variable.
Can you please try the latest version of the plugin?

**Comment by nanego** [comment]
Thanks for reporting the issue.
